


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:


      - name: "xtoph_ocp4 : config-bastion-ntp : populate service facts"
        service_facts:
    
    
    
      - name: "xtoph_ocp4 : config-bastion-ntp : package installation"
        yum: name=chrony state=installed
    
    
    
      ##
      ##    The config should point the local bastion to
      ##    the NTP service defined in master-confg.yml AND
      ##    enable the bastion as a time service provider
      ##
    
    
    
      - name: "xtoph_ocp4 : config-bastion-ntp : deploy ntp/chrony config"
        vars:
          - p_ntp:       "{{ xtoph_ocp4.network.timeserver }}"
          - p_network:   "{{ xtoph_ocp4.network.network_id }}"
          - p_prefix:    "{{ xtoph_ocp4.network.prefix }}"
        template:
          src: "chrony-conf.j2"
          dest: "/etc/chrony.conf"
          owner: root
          group: root
          mode: 644
    
      - name: "xtoph_ocp4 : config-bastion-ntp : restart service"
        service: name=chronyd state=restarted enabled=yes
    
      - name: "xtoph_ocp4 : config-bastion-ntp : add firewalld service rules"
        firewalld:
          service: ntp
          immediate: yes
          permanent: yes
          state: enabled
        when: 
          - ansible_facts['services']['firewalld.service']['state'] is defined
          - ansible_facts['services']['firewalld.service']['state'] == 'running'


