


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : download ocp software [SRC: {{ xtoph_ocp4.ocp_assets.url }}]"
        environment:
          http_proxy:  "{{ xtoph_ocp4.ocp.http_proxy| default('') }}"
          https_proxy: "{{ xtoph_ocp4.ocp.https_proxy| default('') }}"
        get_url:
          url: "{{ xtoph_ocp4.ocp_assets.url }}/{{ item }}"
          dest: "/usr/local/src/{{ item }}"
          mode: "0644"
        with_items:
          - "{{ xtoph_ocp4.ocp_assets.install_tar }}"
        register: openshift_download
        until: openshift_download is not failed
        retries: 5
      
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : unpack ocp software"
        shell:
          cmd: |
            cd /usr/local/bin
            tar zxvf /usr/local/src/{{ item }}
        with_items:
          - "{{ xtoph_ocp4.ocp_assets.install_tar }}"
      
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : additional package installation"
        yum: 
          name: bash-completion
          state: installed

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : additional package installation for SNO support"
        yum: 
          name: podman 
          state: installed
        when: 
          - xtoph_ocp4.ocp.sno == true

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : configure openshift bash completion"
        shell:
          cmd: |
            /usr/local/bin/openshift-install completion bash >> /etc/bash_completion.d/openshift-install_completion

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : Clean-up matchbox ignition directory"
        shell:
          cmd: |
            if [[ -d "/var/lib/matchbox/ignition/" ]] ; then rm -f /var/lib/matchbox/ignition/* ; fi
  



      - name: "xtoph_ocp4 : config-bastion-ocp-upi : load pull secret"
        shell: cat {{ xtoph_ocp4.ocp.creds_dir }}/pull-secret.txt
        register: pull_secret
    
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : load ssh key"
        shell: cat /root/.ssh/id_rsa.pub
        register: ssh_key
  
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : deploy install-config.yml using SDN"
        vars:
          - p_pullSecret:   "{{ pull_secret.stdout |quote }}"
          - p_sshKey:       "{{ ssh_key.stdout |quote }}"
          - p_clusterName:  "{{ xtoph_ocp4.ocp.clustername }}"
          - p_domain:       "{{ xtoph_ocp4.ocp.basedomain }}"
          - p_http_proxy:   "{{ xtoph_ocp4.bastion.squid_http_url if xtoph_ocp4.bastion.squid else xtoph_ocp4.ocp.http_proxy|default('') }}"
          - p_https_proxy:  "{{ xtoph_ocp4.bastion.squid_https_url if xtoph_ocp4.bastion.squid else xtoph_ocp4.ocp.https_proxy|default('') }}"
          - p_no_proxy:     "{{ g_no_proxy | default ('') }}"
          - p_blkdev:       "{{ xtoph_ocp4.rhcos.blk_dev }}"
        template:
          src: "ocp-install-config-sdn.j2"
          dest: "{{ xtoph_ocp4.ocp.creds_dir }}/install-config.yaml"
          owner: root
          group: root
          mode: 644
        when: xtoph_ocp4.ocp.version is version('4.9',operator='<')

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : deploy install-config.yml using OVN"
        vars:
          - p_pullSecret:   "{{ pull_secret.stdout |quote }}"
          - p_sshKey:       "{{ ssh_key.stdout |quote }}"
          - p_clusterName:  "{{ xtoph_ocp4.ocp.clustername }}"
          - p_domain:       "{{ xtoph_ocp4.ocp.basedomain }}"
          - p_http_proxy:   "{{ xtoph_ocp4.bastion.squid_http_url if xtoph_ocp4.bastion.squid else xtoph_ocp4.ocp.http_proxy|default('') }}"
          - p_https_proxy:  "{{ xtoph_ocp4.bastion.squid_https_url if xtoph_ocp4.bastion.squid else xtoph_ocp4.ocp.https_proxy|default('') }}"
          - p_no_proxy:     "{{ g_no_proxy | default ('') }}"
          - p_blkdev:       "{{ xtoph_ocp4.rhcos.blk_dev }}"
        template:
          src: "ocp-install-config-ovn.j2"
          dest: "{{ xtoph_ocp4.ocp.creds_dir }}/install-config.yaml"
          owner: root
          group: root
          mode: 644
        when: xtoph_ocp4.ocp.version is version('4.9',operator='>=')
    
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : Create a backup of the install-config.yaml"
        shell:
          cmd: |
            cp "{{ xtoph_ocp4.ocp.creds_dir }}/install-config.yaml" "{{ xtoph_ocp4.ocp.creds_dir }}/install-config.bak"
  
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : create STANDARD ignition files"
        shell:
          cmd: |
            cd {{ xtoph_ocp4.ocp.creds_dir }}
            /usr/local/bin/openshift-install --dir={{ xtoph_ocp4.ocp.creds_dir }} create ignition-configs
        when: xtoph_ocp4.ocp.sno == false 
          
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : create SNO ignition files"
        shell:
          cmd: |
            cd {{ xtoph_ocp4.ocp.creds_dir }}
            /usr/local/bin/openshift-install --dir={{ xtoph_ocp4.ocp.creds_dir }} create single-node-ignition-config
        when: xtoph_ocp4.ocp.sno == true
          
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : rename signle-node-ignition-config and put copy in assests dir"
        shell:
          cmd: |
            cd {{ xtoph_ocp4.ocp.creds_dir }}
            mv bootstrap-in-place-for-live-iso.ign iso.ign
            cp iso.ign /var/lib/matchbox/assets/
        when: xtoph_ocp4.ocp.sno == true

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : copy ignition files"
        shell:
          cmd: |
            cp {{ xtoph_ocp4.ocp.creds_dir }}/*.ign /var/lib/matchbox/ignition/
    
      - name: "xtoph_ocp4 : config-bastion-ocp-upi : fix ignition file permissions"
        shell:
          cmd: |
            chown matchbox.matchbox /var/lib/matchbox/ignition/*



      - block:

            - name: "xtoph_ocp4 : config-bastion-ocp-upi : DEBUG: general kernel args"
              run_once: false
              debug:
                msg:
                - "ISO Target   = {{ t_dest_iso }}"
                - "USB Delay    = {{ p_usbdelay }}"

            - name: "xtoph_ocp4 : config-bastion-ocp-upi : customize RHCOS ISO image with general kernel args"
              run_once: false
              shell:
                cmd: |
                  cd /var/lib/matchbox/assets/
                  podman run --privileged --pull always --rm \
                      -v /dev:/dev -v /run/udev:/run/udev -v /var/lib/matchbox/assets:/data \
                      -w /data quay.io/coreos/coreos-installer:release \
                      iso kargs modify -a "usb-storage.delay_use={{p_usbdelay}}" {{ t_dest_iso }}

        vars:
          - t_dest_iso:    "{{ xtoph_ocp4.ocp.clustername }}-{{ inventory_hostname_short }}.iso"
          - p_usbdelay:    "{{ xtoph_ocp4.rhcos.usb_delay }}"
        when:
          - xtoph_ocp4.rhcos.nic_mode == "static"
          - inventory_hostname in xtoph_ocp4._cluster_bootstrap + xtoph_ocp4._cluster_masters + xtoph_ocp4._cluster_workers + xtoph_ocp4._cluster_sno



      - block:

            - name: "xtoph_ocp4 : config-bastion-ocp-upi : DEBUG: ISO customization network parameters"
              run_once: false
              debug:
                msg:
                - "ISO Target   = {{ t_dest_iso }}"
                - "NIC Mode     = {{ xtoph_ocp4.rhcos.nic_mode }}" 
                - "ISO Name     = {{ t_dest_iso }}"
                - "DNS          = {{ p_dns }}"
                - "RHCOS Device = {{ p_dev }}"
                - "RHCOS DHCP   = {{ p_ip_dhcp }}"
                - "RHCOS STATIC = {{ p_ip_static }}"

            - name: "xtoph_ocp4 : config-bastion-ocp-upi : customize RHCOS ISO image with kernel args for DHCP IP"
              run_once: false
              shell:
                cmd: |
                  cd /var/lib/matchbox/assets/
                  podman run --privileged --pull always --rm \
                      -v /dev:/dev -v /run/udev:/run/udev -v /var/lib/matchbox/assets:/data \
                      -w /data quay.io/coreos/coreos-installer:release \
                      iso kargs modify -a "ip={{ p_ip_dhcp }}" {{ t_dest_iso }}
              when:
                - xtoph_ocp4.rhcos.nic_mode != "static"

            - name: "xtoph_ocp4 : config-bastion-ocp-upi : customize RHCOS ISO image with kernel args for STATIC IP"
              run_once: false
              shell:
                cmd: |
                  cd /var/lib/matchbox/assets/
                  podman run --privileged --pull always --rm \
                      -v /dev:/dev -v /run/udev:/run/udev -v /var/lib/matchbox/assets:/data \
                      -w /data quay.io/coreos/coreos-installer:release \
                      iso kargs modify -a "ip={{ p_ip_static }}" {{ t_dest_iso }}
              when:
                - xtoph_ocp4.rhcos.nic_mode == "static"

        vars:
          - t_dest_iso:    "{{ xtoph_ocp4.ocp.clustername }}-{{ inventory_hostname_short }}.iso"
          - p_dns:         "{{ xtoph_ocp4.bastion.host_ip if xtoph_ocp4.bastion.dns == true else xtoph_ocp4.network.nameserver }}"
#          - p_dev:         "{{ xtoph_ocp4.rhcos.nic_dev | regex_replace('^(.*):dhcp$','\\1') }}"
          - p_dev:         "{{ xtoph_ocp4.rhcos.nic_dev | regex_replace('^(.*):.*','\\1') }}"
          - p_ip_dhcp:     "{{ p_dev }}:dhcp"
          - p_ip_static:   "{{ h_pubIP  }}::{{ xtoph_ocp4.network.gateway }}:{{ xtoph_ocp4.network.gateway }}:{{ inventory_hostname }}:{{ p_dev }}:none:{{ p_dns }}"
        when:
          - inventory_hostname in xtoph_ocp4._cluster_bootstrap + xtoph_ocp4._cluster_masters + xtoph_ocp4._cluster_workers + xtoph_ocp4._cluster_sno


      - name: "xtoph_ocp4 : config-bastion-ocp-upi : customize SNO ISO image with embedded ignition"
        run_once: false
        vars:
          - t_dest_iso:    "{{ xtoph_ocp4.ocp.clustername }}-{{ inventory_hostname_short }}.iso"
        shell:
          cmd: |
            cd /var/lib/matchbox/assets/
            podman run --privileged --rm \
                -v /dev:/dev -v /run/udev:/run/udev -v /var/lib/matchbox/assets:/data \
                -w /data quay.io/coreos/coreos-installer:release \
                iso ignition embed -fi iso.ign {{ t_dest_iso }}
        when:
          - xtoph_ocp4.ocp.sno == true
          - inventory_hostname in xtoph_ocp4._cluster_sno

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : cleanup signle-node-ignition-config in assests dir"
        shell:
          cmd: |
            rm -f  /var/lib/matchbox/assets/iso.ign
        when: xtoph_ocp4.ocp.sno == true

      ## Maybe matchbox needs a refresh of content updates, so just to be safe... restart

      - name: "xtoph_ocp4 : config-bastion-ocp-upi : restart matchbox services"
        service: name="{{ item }}" state=restarted enabled=yes daemon_reload=yes
        with_items:
          - "matchbox"
        when: xtoph_ocp4.bastion.matchbox == true


  #
  #    Only execute tasks if workshop_lock == false
  #

  when:
    - workshop_lock == false

      

