


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:



      - name: "ocp4-workshop : bastion-squid : populate service facts"
        service_facts:
    
    

      - name: "ocp4-workshop : bastion-squid : package installation"
        yum: name=squid state=installed
    
    
    
      - name: "ocp4-workshop : bastion-squid : enable squid cache_dir"
        replace:
          path: '/etc/squid/squid.conf'
          regexp: '^#cache_dir (.*)$'
          replace: 'cache_dir \1'
    
    
    
      - name: "ocp4-workshop : bastion-squid : restart services"
        service: name=squid state=restarted enabled=yes masked=no
    
    
    
      - name: "ocp4-workshop : bastion-squid : add firewalld ports and services"
        firewalld:
          service: "squid"
          immediate: yes
          permanent: yes
          state: enabled
        when: 
          - ansible_facts['services']['firewalld.service']['state'] is defined
          - ansible_facts['services']['firewalld.service']['state'] == 'running'
