 


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  block:


      - name: "xtoph_ocp4 : config-bastion-tests : test fqdn lookup of all nodes"
        vars: 
          - p_server:  "localhost"
          - p_name:    "{{ inventory_hostname }}"
          - p_addr:    "{{ h_pubIP }}"
          - p_domain:  "{{ xtoph_ocp4.ocp.cluster_fqdn }}"
        when:
          - workshop_vars.bastion.dns == true
        shell: 
          cmd: |
            dig @{{ p_server }} {{ p_name }} +short
            dig -x @{{ p_server }} {{ p_addr }} +short
        loop: "{{ _cluster_bootstrap + _cluster_masters + _cluster_workers }}"
        changed_when: false



      - name: "xtoph_ocp4 : config-bastion-tests : test wildcard"
        run_once: true
        vars: 
          - p_server:  "localhost"
          - p_name:    "foo"
          - p_domain:  "{{ xtoph_ocp4.ocp.wildcard_fqdn }}"
        when:
          - workshop_vars.bastion.dns == true
        shell: 
          cmd: |
            dig @{{ p_server }} {{ p_name }}.{{ p_domain }} +short
        changed_when: false



      - name: "xtoph_ocp4 : config-bastion-tests : test api"
        run_once: true
        vars: 
          - p_server:  "localhost"
          - p_name:    "api"
          - p_domain:  "{{ xtoph_ocp4.ocp.cluster_fqdn }}"
        when:
          - workshop_vars.bastion.dns == true
        shell: 
          cmd: |
            dig @{{ p_server }} {{ p_name }}.{{ p_domain }} +short
        changed_when: false



      - name: "xtoph_ocp4 : config-bastion-tests : test api-int"
        run_once: true
        vars: 
          - p_server:  "localhost"
          - p_name:    "api-int"
          - p_domain:  "{{ xtoph_ocp4.ocp.cluster_fqdn }}"
        when:
          - workshop_vars.bastion.dns == true
        shell: 
          cmd: |
            dig @{{ p_server }} {{ p_name }}.{{ p_domain }} +short
        changed_when: false



      - name: "xtoph_ocp4 : config-bastion-tests : test quay.io"
        run_once: true
        vars: 
          - p_server:  "localhost"
          - p_name:    "quay.io"
        when:
          - xtoph_ocp4.bastion.dns  == true
        shell: 
          cmd: |
            dig @{{ p_server }} {{ p_name }} +short
        changed_when: false

