


#
#    Try loading the credentials.yml file
#    if workshopuser_username is not defined
#



- name: "xtoph_ocp4 : config-bastion-workshop-user : loading credentials"
  include_vars:
    file: "./config/credentials.yml"
  when: workshopuser_username is undefined



#
#    Only execute these blocked tasks 
#    if workshopuser_username is defined
#



- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:



      #
      # We need some Ansible facts for tasks below
      #


      - setup:



      - name: "xtoph_ocp4 : config-bastion-workshop-user : create workshopuser-username GID"
        group:
          name: "{{ workshopuser_username }}"
          state: present
    
    
    
      - name: "xtoph_ocp4 : config-bastion-workshop-user : create workshopuser-username UID"
        vars:
          t_pass:  "{{ workshopuser_password | default(lookup('password', '/dev/null length=15 chars=ascii_letters')) }}"
        user:
          name: "{{ workshopuser_username }}"
          password: "{{ t_pass | password_hash('sha512') }}"
          group: "{{ workshopuser_username }}"
          state: present
    
    
    
      - name: "xtoph_ocp4 : config-bastion-workshop-user : add sudo configuration"
        vars:
          t_name: "{{ workshopuser_username }}"
        template:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          mode: 0600
        with_items:
          - {src: 'sudoers.j2', dest: '/etc/sudoers.d/ocp4-workshop'}
          - {src: 'sudoers-student.j2', dest: '/etc/sudoers.d/{{ t_name }}'}
   


      - name: "xtoph_ocp4 : config-bastion-workshop-user : create ~Desktop directory"
        file:
          path:  "~{{ workshopuser_username }}/Desktop"
          mode:  "0755"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          state: directory
    
    
    
      - name: "xtoph_ocp4 : config-bastion-workshop-user : create friendly openshift console shortcut on desktop (RHEL 7)"
        vars:
          - t_link: "console-openshift-console.{{ xtoph_ocp4.ocp.wildcard_fqdn }}"
        template:
          src:   "{{ item.src }}"
          dest:  "~{{ workshopuser_username }}/Desktop/{{ item.dst }}"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          mode: 0744
        with_items:
          - { src: "workshopuser-console-link-rhel7.j2",  dst: "OCP-Console.desktop" }
          - { src: "workshopuser-terminal-link-rhel7.j2", dst: "Terminal.desktop" }
        when:
          - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
          - ansible_distribution_major_version == "7"
   


      - name: "xtoph_ocp4 : config-bastion-workshop-user : create friendly openshift console shortcut on desktop (RHEL 8)"
        vars:
          - t_link: "console-openshift-console.{{ xtoph_ocp4.ocp.wildcard_fqdn }}"
        template:
          src:   "{{ item.src }}"
          dest:  "~{{ workshopuser_username }}/Desktop/{{ item.dst }}"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          mode: 0744
        with_items:
          - { src: "workshopuser-console-link-rhel8.j2",  dst: "OCP-Console.desktop" }
          - { src: "workshopuser-terminal-link-rhel8.j2", dst: "Terminal.desktop" }
        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "8"


      
      - name: "xtoph_ocp4 : config-bastion-workshop-user : create AccountService directory (RHEL 8)"
        file:
          path:  "/var/lib/AccountsService/users/"
          mode:  "0755"
          owner: "root"
          group: "root"
          state: directory
        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "8"
    


      - name: "xtoph_ocp4 : config-bastion-workshop-user : select classic gnome desktop for workshopuser (RHEL 8)"
        template:
          src: "workshopuser-classic-desktop.j2"
          dest: "/var/lib/AccountsService/users/{{ workshopuser_username }}"
          owner: "root"
          group: "root"
          mode: 0644
        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "8"



      - name: "xtoph_ocp4 : config-bastion-workshop-user : adjust vncusers config (RHEL 8)"
        lineinfile:
          dest:  "~{{ workshopuser_username }}/.bash_profile"
          line:  "export GNOME_SHELL_SESSION_MODE=classic"
          state: present



  when: workshopuser_username is defined

