


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:


      - name: "xtoph_ocp4 : config-bastion-ntp : populate service facts"
        service_facts:
    
    
    
      - name: "xtoph_ocp4 : config-bastion-ntp : package installation"
        yum: name=chrony state=installed
    
    
    
      ##
      ##    The config should point the local bastion to
      ##    the NTP service defined in master-confg.yml AND
      ##    enable the bastion as a time service provider
      ##
    
    
    
      - name: "xtoph_ocp4 : config-bastion-ntp : deploy ntp/chrony config"
        vars:
          - p_ntp:       "{{ xtoph_ocp4.network.timeserver }}"
          - p_network:   "{{ xtoph_ocp4.network.network_id }}"
          - p_prefix:    "{{ xtoph_ocp4.network.prefix }}"
        template:
          src: "chrony-conf.j2"
          dest: "/etc/chrony.conf"
          owner: root
          group: root
          mode: 644
    
      - name: "xtoph_ocp4 : config-bastion-ntp : restart service"
        service: name=chronyd state=restarted enabled=yes
    
      - name: "xtoph_ocp4 : config-bastion-ntp : add firewalld service rules"
        firewalld:
          service: ntp
          immediate: yes
          permanent: yes
          state: enabled
        when: 
          - ansible_facts['services']['firewalld.service']['state'] is defined
          - ansible_facts['services']['firewalld.service']['state'] == 'running'

      ##
      ##    NTP/Chrony config for OCP nodes should:
      ##        use bastion service if bastion.ntp is true, OR
      ##        user defined timeserver, OR 
      ##        point to the redhat ntp pool (handled in template)
      ##

      - name: "xtoph_ocp4 : config-bastion-workshop-materials : install workshop-(yaml's) in /usr/local/etc"
        vars:
          - p_server:      "{{ xtoph_ocp4.bastion.host_ip }}"
          - p_timeserver:  "{{ xtoph_ocp4.bastion.host_ip if xtoph_ocp4.bastion.ntp == true else xtoph_ocp4.network.timeserver }}"
          - p_chrony_conf: "{{ lookup('template', 'workshop-config-chrony-conf.j2') | b64encode }}"
        template:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          mode: 0644
        with_items:
          - {src: 'workshop-config-chrony-machineconfig-masters.j2',      dest: '/usr/local/etc/workshop-chrony-machineconfig-masters.yaml'}
          - {src: 'workshop-config-chrony-machineconfig-workers.j2',      dest: '/usr/local/etc/workshop-chrony-machineconfig-workers.yaml'}

