
- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:



      - name: "xtoph_ocp4 : preinstall-workers : wait for availability of config-server on masters"
        wait_for:
          host: "{{ hostvars[item]['h_pubIP'] }}"
          connect_timeout: 5
          delay: 3
          port: 22623
          sleep: 5
          state: started
          timeout: 1800
        loop: "{{ xtoph_ocp4._cluster_masters | difference(xtoph_ocp4._cluster_bootstrap) }}"

