


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:

      #
      #    Run this block only if install method 
      #    is UPI (not assisted_installer AI)
      #

      - debug:
          msg:
            - "DEBUG: ***"
            - "DEBUG: *** PREINSTALL-NODE: {{ inventory_hostname }}"
            - "DEBUG: *** {{ xtoph_ocp4_action }} /  {{ xtoph_ocp4_subaction | default('') }}"
            - "DEBUG: ***"



      #
      # bootstrap (flip)
      #

      - block:

            #
            #    generic set of tests to verify bastion 
            #    services are up prior to starting
            #    bootstrap deployment
            #

            - name: "xtoph_ocp4 : preinstall-node (bootstrap) : test DNS port on bastion"
              when: xtoph_ocp4.bastion.dns == true
              wait_for:
                host: "{{ xtoph_ocp4.bastion.host_fqdn }}"
                connect_timeout: 5
                delay: 3
                port: 53 
                sleep: 1
                state: started
                timeout: 30
          
            - name: "xtoph_ocp4 : preinstall-node (bootstrap) : test MATCHBOX port on bastion"
              when: xtoph_ocp4.bastion.matchbox == true
              wait_for:
                host: "{{ xtoph_ocp4.bastion.host_fqdn }}"
                connect_timeout: 5
                delay: 3
                port: "{{ xtoph_ocp4.bastion.matchbox_port }}"
                sleep: 1
                state: started
                timeout: 30

            - block:

                  #    
                  #    Here we 'flip' either a worker's or master's normal ignition with     
                  #    bootstrap.ign.  Now the flipped node will be the bootstrap.
                  #    When the control plane is online, we 'flop' back
                  #    and redeploy (search 'bootstrap-flop' below)
                  #
                  #        NOTE: flipping a master only works with OCP > 4.11
                  #

                  - name: "xtoph_ocp4 : preinstall-node (bootstrap-flip) : flip worker node profile to bootstrap"
                    vars:
                      - t_profile:   "worker"
                      - t_name:      "{{ inventory_hostname_short }}"
                    replace:
                      path:    "/var/lib/matchbox/profiles/{{ t_profile }}-{{ t_name }}.json"
                      regexp:  '(.*)worker\.ign(.*)'
                      replace: '\1bootstrap.ign\2'
                    when:
                      - inventory_hostname in xtoph_ocp4._cluster_workers 

                  - name: "xtoph_ocp4 : preinstall-node (bootstrap-flip) : flip master node profile to bootstrap"
                    vars:
                      - t_profile:   "master"
                      - t_name:      "{{ inventory_hostname_short }}"
                    replace:
                      path:    "/var/lib/matchbox/profiles/{{ t_profile }}-{{ t_name }}.json"
                      regexp:  '(.*)master\.ign(.*)'
                      replace: '\1bootstrap.ign\2'
                    when:
                      - inventory_hostname in xtoph_ocp4._cluster_masters 

                  - name: "xtoph_ocp4 : preinstall-node (bootstrap-flip) : enable and restart matchbox service"
                    service: 
                      name: "matchbox" 
                      state: restarted 
                      enabled: yes 

              when:
                - inventory_hostname in xtoph_ocp4._cluster_masters or
                  inventory_hostname in xtoph_ocp4._cluster_workers 
      
        when: 
          - inventory_hostname in xtoph_ocp4._cluster_bootstrap or
            inventory_hostname in xtoph_ocp4._cluster_bootstrap_flipflop
          - xtoph_ocp4_subaction is defined and xtoph_ocp4_subaction == "preinstall-bootstrap"


      # 
      # masters
      # 

      - block:

            #
            #    Because the bootstrap disables itself once
            #    masters are online, test if masters already 
            #    provide config-service.  Otherwise, you
            #    wind up waiting for the bootstrap which will
            #    never come.
            #
      
            - name: "xtoph_ocp4 : preinstall-node (master) : verify CONFIG SERVER port on masters is NOT active"
              ignore_errors: true
              wait_for:
                host: "{{ item }}"
                connect_timeout: 5 
                delay: 3
                port: "22623"
                sleep: 1
                state: started
                timeout: 15
              register: config_service_master
              loop: "{{ xtoph_ocp4._cluster_masters | difference(xtoph_ocp4._cluster_bootstrap_flipflop) }}"
      
            - debug: var=config_service_master
              when: xtoph_ocp4._debug == true
      
            #
            #    wait here until BOOTSTRAP provides config-service, 
            #    unless masters are already online providing config-service
            #
      
            - name: "xtoph_ocp4 : preinstall-node (master) : wait for  CONFIG SERVER port on bootstrap"
              run_once: true
              wait_for:
                host: "{{ item }}"
                connect_timeout: 5
                delay: 3
                port: "22623"
                sleep: 1
                state: started
                timeout: 1800 
              register: config_service_bootstrap
              loop: "{{ xtoph_ocp4._cluster_bootstrap + xtoph_ocp4._cluster_bootstrap_flipflop }}"
              when: config_service_master.failed is defined
      
            - debug: var=config_service_bootstrap
              when: xtoph_ocp4._debug == true

        when: 
          - inventory_hostname in xtoph_ocp4._cluster_masters
          - inventory_hostname not in xtoph_ocp4._cluster_bootstrap_flipflop
          - xtoph_ocp4_subaction is defined and xtoph_ocp4_subaction == "preinstall-masters"



      #
      #  bootstrap (flop)
      #

      - block:

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) :  (NEW) launch async openshift-install wait-for"
              run_once: true
              delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
              async: 3600
              poll: 0
              shell:
                cmd: |
                  cd {{xtoph_ocp4.ocp.creds_dir}}
                  touch I_was_here.txt
                  openshift-install wait-for bootstrap-complete 

            #
            #  This is an older test I used to determine when the bootstrap was done
            #  it worked sufficiently until 4.16
            #

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) :  wait for config-service shutdown on bootstrap"
              wait_for:
                host: "{{ hostvars[item]['h_pubIP'] }}"
                connect_timeout: 5
                delay: 3
                port: 22623
                sleep: 5
                state: stopped
                timeout: 1800
              loop: "{{ xtoph_ocp4._cluster_bootstrap_flipflop }}"

            #
            #  Another test that's closer the completion of bootstrap activity
            #  Added while I was trying to solve problems with 4.16
            #

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) :  wait for api-service shutdown on bootstrap"
              wait_for:
                host: "{{ hostvars[item]['h_pubIP'] }}"
                connect_timeout: 5
                delay: 3
                port: 6443
                sleep: 5
                state: stopped
                timeout: 1800
              loop: "{{ xtoph_ocp4._cluster_bootstrap_flipflop }}"

            #
            #  Resorting to openshift-install tool to detect bootstrap completion and report status
            #  to the log.  NOTE that the 'wait-for' action was forked off a few tasks above.
            #

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) :  (NEW) wait for 'Bootstrap status: complete' in .openshift_install.log"
              run_once: true
              delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
              wait_for:
                path: "{{xtoph_ocp4.ocp.creds_dir}}/.openshift_install.log"
                search_regex: "Bootstrap status: complete"
                sleep: 5
                timeout: 1800

            - name: "xtoph_ocp4 : preistall-node (bootstrap-flop) : issue graceful shutdown to bootstrap"
              run_once: true
              delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
              shell:
                cmd: |
                  ssh core@{{ inventory_hostname }} sudo systemctl -f poweroff

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) : wait for OCP node systemd port stopped"
              run_once: true
              wait_for:
                host: "{{ inventory_hostname }}"
                connect_timeout: 3
                port: 111
                sleep: 5
                state: stopped
                timeout: 180
              ignore_errors: yes

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) : revert worker node profile back to worker.ign"
              vars:
                - t_profile:   "worker"
                - t_name:      "{{ inventory_hostname_short }}"
              replace:
                path:    "/var/lib/matchbox/profiles/{{ t_profile }}-{{ t_name }}.json"
                regexp:  '(.*)bootstrap\.ign(.*)'
                replace: '\1worker.ign\2'
              when:
                - inventory_hostname in xtoph_ocp4._cluster_workers

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) : revert master node profile back to master.ign"
              vars:
                - t_profile:   "master"
                - t_name:      "{{ inventory_hostname_short }}"
              replace:
                path:    "/var/lib/matchbox/profiles/{{ t_profile }}-{{ t_name }}.json"
                regexp:  '(.*)bootstrap\.ign(.*)'
                replace: '\1master.ign\2'
              when:
                - inventory_hostname in xtoph_ocp4._cluster_masters

            - name: "xtoph_ocp4 : preinstall-node (bootstrap-flop) : enable and restart matchbox service"
              run_once: true
              service: 
                name: "matchbox" 
                state: restarted 
                enabled: yes 

            ##
            ## it appears we need to remove the bootstrap from the
            ## etcd member list to free up the spot which the rebuilt master will take over
            ##
            ## Starting in 4.16, without cleaning up etcd the cluster will not complete loading of cluster-operators
            ##
            ##
            ## Summary: 
            ##     oc rsh -n openshift-etcd etcd-master2.ocpdemo10g.lab.linuxsoup.com
            ##     etcdctl member list | grep <get the id>
            ##     etcdctl member remove <id>
            ##
            ## steps to do so are located here: https://access.redhat.com/solutions/5498971
            ##
            ## EXAMPLE: 
            ##          [root@bastion ~]# oc get nodes
            ##          NAME                                   STATUS   ROLES                         AGE   VERSION
            ##          master2.ocpdemo10g.lab.linuxsoup.com   Ready    control-plane,master,worker   15m   v1.28.8+8974577
            ##          master3.ocpdemo10g.lab.linuxsoup.com   Ready    control-plane,master,worker   15m   v1.28.8+8974577
            ##          [root@bastion ~]# oc get pods -A | grep etcd
            ##          openshift-etcd-operator                            etcd-operator-55fb59f9cf-b2fvj                                        1/1     Running            2 (29s ago)     14m
            ##          openshift-etcd                                     etcd-guard-master2.ocpdemo10g.lab.linuxsoup.com                       1/1     Running            0               9m54s
            ##          openshift-etcd                                     etcd-guard-master3.ocpdemo10g.lab.linuxsoup.com                       1/1     Running            0               6m43s
            ##          openshift-etcd                                     etcd-master2.ocpdemo10g.lab.linuxsoup.com                             4/4     Running            0               11s
            ##          openshift-etcd                                     etcd-master3.ocpdemo10g.lab.linuxsoup.com                             4/4     Running            0               6m49s
            ##          openshift-etcd                                     installer-1-master2.ocpdemo10g.lab.linuxsoup.com                      0/1     Completed          0               10m
            ##          openshift-etcd                                     installer-3-master3.ocpdemo10g.lab.linuxsoup.com                      0/1     Completed          0               7m47s
            ##          openshift-etcd                                     installer-6-master2.ocpdemo10g.lab.linuxsoup.com                      0/1     Completed          0               4m21s
            ##          [root@bastion ~]# oc rsh -n openshift-etcd etcd-master2.ocpdemo10g.lab.linuxsoup.com
            ##          sh-5.1# etcdctl member list
            ##          14181bed13b89d5e, started, etcd-bootstrap, https://192.168.100.82:2380, https://192.168.100.82:2379, false
            ##          2cf0879bb08985a1, started, master3.ocpdemo10g.lab.linuxsoup.com, https://192.168.100.84:2380, https://192.168.100.84:2379, false
            ##          81f85a00e83e89a5, started, master2.ocpdemo10g.lab.linuxsoup.com, https://192.168.100.83:2380, https://192.168.100.83:2379, false
            ##          sh-5.1# etcdctl member remove 14181bed13b89d5e
            ##          Member 14181bed13b89d5e removed from cluster 3b77626e9fed89a6
            ##          sh-5.1#
            ##


        when:
          - inventory_hostname in xtoph_ocp4._cluster_bootstrap_flipflop
          - xtoph_ocp4_subaction is defined and xtoph_ocp4_subaction == "preinstall-bootstrap-flop"



      ##
      ##  workers
      ##

      - block:

            #
            #    wait here until MASTERS provide config-service 
            #
      
            - name: "xtoph_ocp4 : preinstall-node : (worker) wait for availability of config-server on masters"
              wait_for:
                host: "{{ hostvars[item]['h_pubIP'] }}"
                connect_timeout: 5
                delay: 3
                port: 22623
                sleep: 5
                state: started
                timeout: 1800
              loop: "{{ xtoph_ocp4._cluster_masters | difference(xtoph_ocp4._cluster_bootstrap_flipflop) }}"

        when: 
          - inventory_hostname in xtoph_ocp4._cluster_workers 
          - xtoph_ocp4_subaction is defined and xtoph_ocp4_subaction == "preinstall-workers"



  when: xtoph_ocp4.bastion.assisted_installer is undefined or
        xtoph_ocp4.bastion.assisted_installer == false



