- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  run_once: true
  block:


      #
      #    If this is an assisted-installer 
      #    we have a chance to clean up cluster configuration
      #    in the AI portal
      #

      - name: "xtoph_ocp4 : preunistall-node-shutdown : load ocm offline token"
        shell: cat {{ xtoph_ocp4.ocp.creds_dir }}/ocm-token.txt
        register: ocm_token

      - name: "xtoph_ocp4 : preunistall-node-shutdown : delete cluster configuration (ignore error if it does not)"
        shell:
          cmd: |
            aicli --offlinetoken {{ ocm_token.stdout|quote }}      \
                delete cluster {{ xtoph_ocp4.ocp.clustername }} -y
        ignore_errors: true

  when:
    - xtoph_ocp4.bastion.assisted_installer == true





- delegate_to: localhost 
  block:

      - name: "xtoph_ocp4 : preunistall-node-shutdown : test existence of node via ssh port"
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      #
      #    Remove the openshift deployment lock
      #

      - name: "xtoph_ocp4: config-bastion-ocp-unlock : remove lock ({{ workshop_extras.ocp_creds_dir }}/xtoph_ocp4_deployment.lock)"
        file:
          path:  "{{ xtoph_ocp4.ocp.creds_dir }}/xtoph_ocp4_deployment.lock"
          state: absent

      #
      #    Proceed with node shutdown and wait
      #

      - name: "xtoph_ocp4 : preunistall-node-shutdown : issue gracefull OCP node shutdown"
        delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
        shell:
          cmd: |
            ssh core@{{ inventory_hostname_short }}.{{xtoph_ocp4.ocp.cluster_fqdn }} nohup 'sleep 3 && sudo shutdown -h now' &

      - name: "xtoph_ocp4 : preunistall-node-shutdown : wait for OCP node systemd port stopped"
        wait_for:
          host: "{{ inventory_hostname_short }}.{{xtoph_ocp4.ocp.cluster_fqdn }}"
          connect_timeout: 3
          port: 111
          sleep: 5
          state: stopped
          timeout: 180
        ignore_errors: yes

  rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



