


- delegate_to: "{{ xtoph_ocp4.bastion.host_fqdn }}"
  block:

      - name: "xtoph_ocp4 : preunistall-node-shutdown : test existence of node via ssh port"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "xtoph_ocp4 : preunistall-node-shutdown : issue gracefull shutdown"
        shell:
          cmd: |
            ssh core@{{ inventory_hostname_short }}.{{xtoph_ocp4.ocp.cluster_fqdn }} nohup 'sleep 3 && sudo shutdown -h now' &

      - name: "xtoph_ocp4 : preunistall-node-shutdown : wait for systemd port stopped"
        delegate_to: localhost
        wait_for:
          host: "{{ inventory_hostname_short }}.{{xtoph_ocp4.ocp.cluster_fqdn }}"
          connect_timeout: 3
          port: 111
          sleep: 5
          state: stopped
          timeout: 180
        ignore_errors: yes

  rescue:

      - debug: msg="node {{inventory_hostname}} is already down"



